// вместо Api

export const imagesArrow = {
  images: [
    {
      link: "https://i.ytimg.com/vi/ZQwrnyemuvA/maxresdefault.jpg",
      id: 0,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "grid",
        "flex",
        "flexbox",
        "rubber",
        "rubber adaptive",
        "adaptive",
        "Properties",
        "Responsive Design",
        "Outside",
        "Inside",
        "List Item",
        "Iternal",
        "Box",
        "Legacy",
        "inline",
      ],
    },
    {
      link: "https://www.bitdegree.org/learn/storage/media/images/661999ba-c216-4c71-b959-82f878309730.o.png",
      id: 1,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "Responsive Design",
        "rubber",
        "rubber adaptive",
        "Box",
        "flexbox",
      ],
    },
    {
      link: "https://images.viblo.asia/retina/793009f7-e87b-4ec9-9bb7-7523229a89dd.png",
      id: 2,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "Responsive Design",
        "rubber",
        "rubber adaptive",
        "Box",
        "flexbox",
        "stretch",
        "baseline",
        "center",
        "flex-start",
        "flex-end",
      ],
    },
    {
      link: "https://preview.redd.it/rofzm44oka091.png?auto=webp&s=99a6ec87e79b8ad7d6b614c95e8a65933fadca4d",
      id: 3,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "Responsive Design",
        "rubber",
        "rubber adaptive",
        "Box",
        "flexbox",
        "stretch",
        "baseline",
        "center",
        "flex-start",
        "flex-end",
        "row",
        "column",
        "row-reverse",
        "column-reverse",
        "space-around",
        "space-evenly",
        "space-between",
        "space-around",
      ],
    },
    {
      link: "https://d585tldpucybw.cloudfront.net/sfimages/default-source/blogs/2020/2020-10/flexbox-compared-css-grid.png",
      id: 4,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "Responsive Design",
        "grid",
        "css grid",
      ],
    },
    {
      link: "https://htmlandcssguidebook.com/images/align-items.png",
      id: 5,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "Responsive Design",
        "grid",
        "css grid",
        "flexbox",
        "stretch",
        "baseline",
        "center",
      ],
    },
    {
      link: "https://fuzeservers.ru/wp-content/uploads/2/1/7/2170a5a68d2a751f021557e358e9d605.jpeg",
      id: 6,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "Responsive Design",
        "grid",
        "center",
        "16:9",
        "horizontal",
        "vertical",
        "masonry",
      ],
    },
    {
      link: "https://miro.medium.com/max/1280/1*I3fajLsIJxXjdpThL1ZTaQ.png",
      id: 7,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "flexbox",
        "flex-items",
        "items",
      ],
    },
    {
      link: "https://fuzeservers.ru/wp-content/uploads/a/6/e/a6e8d5c56922fac1f58a319e44e8e3d8.png",
      id: 8,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "flexbox",
        "flex-items",
        "items",
        "stretch",
        "baseline",
        "center",
        "aling-self",
        "flex-start",
        "flex-end",
      ],
    },
    {
      link: "https://bootstrapcreative.com/wp-bc/wp-content/uploads/2017/11/Screen-Shot-2017-11-07-at-11.27.06-PM.png",
      id: 9,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "flexbox",
        "flex-direction",
        "row",
        " column",
        "row-reverse",
        "column-reverse",
      ],
    },
    {
      link: "https://minya01.github.io/assets/images/flexbox-use.jpg",
      id: 10,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "flexbox",
        "alingment",
        "direction",
        "order",
        "size",
      ],
    },
    {
      link: "https://www.webcreatorbox.com/wp-content/uploads/2017/03/align-items-1.png",
      id: 11,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "flexbox",
        "stretch",
        "flex-start",
        "flex-end",
        "center",
        " baseline",
      ],
    },
    {
      link: "https://1.bp.blogspot.com/-d_6YTUtx7gQ/XpvAOtr2xWI/AAAAAAAAANI/zSyPKIi44qQzg78XQ8RAMR7CZxhGM32UACLcBGAsYHQ/s1600/Container.png",
      id: 12,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "flexbox",
        "container",
      ],
    },
    {
      link: "http://blogs.quovantis.com/wp-content/uploads/2017/06/Understanding-Flexbox_Flex-Direction.png",
      id: 13,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "flexbox",
        "flex-direction",
        "row",
        " column",
        "row-reverse",
        "column-reverse",
      ],
    },
    {
      link: "https://cdn.hashnode.com/res/hashnode/image/upload/v1669021824672/9FoLl6GdV.png?auto=compress,format&format=webp",
      id: 14,
      keywords: ["flex", "box", "flexbox", "gap", "px"],
    },
    {
      link: "https://i.stack.imgur.com/VmTfp.png",
      id: 15,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "flexbox",
        "space-between",
        "space-around",
        "space-evenly",
      ],
    },
    {
      link: "https://miro.medium.com/v2/resize:fit:2400/1*U5EHP2ze4IJoHpzO754TyA.png",
      id: 16,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "flexbox",
        "px",
        "em",
      ],
    },
    {
      link: "https://www.elmastudio.de/wp-content/uploads/2012/07/css-rem-01.jpg",
      id: 17,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "flexbox",
        "px",
        "em",
        "rem",
      ],
    },
    {
      link: "https://dev-to-uploads.s3.amazonaws.com/i/z094e3wehsoe8z6lsxnz.png",
      id: 18,
      keywords: [
        "css",
        "scss",
        "less",
        "sass",
        "flex",
        "box",
        "flexbox",
        "flex-grow",
        "flex-shrink",
      ],
    },
    {
      link: "https://dev-to-uploads.s3.amazonaws.com/i/z094e3wehsoe8z6lsxnz.png",
      id: 19,
      keywords: ["js", "javascript", "map", "filter", "find", "reduce"],
    },
    {
      link: "http://i1.ytimg.com/vi/EzB6Pk66XW8/maxresdefault.jpg",
      id: 20,
      keywords: ["js", "javascript", "map", "filter", "reduce"],
    },
    {
      link: "https://media.tproger.ru/uploads/2022/05/JavaScript.png",
      id: 21,
      keywords: ["js", "javascript", "LocalStorage", "webApi", "Api"],
    },
    {
      link: "https://cdn.hackernoon.com/images/uaPC3alJGZYWa8bXdj0MJNXLMDC2-el3335y9.jpeg",
      id: 22,
      keywords: [
        "js",
        "javascript",
        "LocalStorage",
        "webApi",
        "Api",
        "Request",
        "Response",
        "web server",
        "database",
      ],
    },
    {
      link: "https://avatars.mds.yandex.net/i?id=fdad82085a8323e0d452f4fe23e0b2e75ba2b124-10176094-images-thumbs&n=13",
      id: 23,
      keywords: [
        "js",
        "javascript",
        "LocalStorage",
        "webApi",
        "Api",
        "Request",
        "Response",
        "web server",
        "database",
      ],
    },
    {
      link: "https://raw.githubusercontent.com/komushi/gnavi-mongo/master/images/architecture.png",
      id: 24,
      keywords: [
        "js",
        "javascript",
        "LocalStorage",
        "webApi",
        "Api",
        "Request",
        "database",
        "node",
      ],
    },
    {
      link: "https://i.pinimg.com/originals/fb/74/1d/fb741de7aa37562e0b31111f17f2d733.png",
      id: 25,
      keywords: [
        "js",
        "javascript",
        "LocalStorage",
        "webApi",
        "Api",
        "Request",
        "database",
        "node",
      ],
    },
    {
      link: "https://i.pinimg.com/originals/20/8b/d9/208bd9650ddf9a7952e561a41d2d27e0.png",
      id: 26,
      keywords: [
        "js",
        "javascript",
        "LocalStorage",
        "webApi",
        "Api",
        "Request",
        "database",
        "node",
      ],
    },
    {
      link: "https://preview.redd.it/z5n8hy63vr381.png?auto=webp&s=20f5a17ff7ac3a31d937a020345b989f8fbf54cd",
      id: 27,
      keywords: [
        "js",
        "javascript",
        "map",
        "filter",
        "reduce",
        "find",
        "findIndexOf",
        "fill",
        "some",
        "every",
      ],
    },
    {
      link: "https://avatars.mds.yandex.net/i?id=2a0000018b248e65ff8109e4b47004b09fe7-1463148-fast-images&n=13",
      id: 28,
      keywords: ["js", "javascript", "array", "every", "function"],
    },
    {
      link: "http://images.myshared.ru/6/712576/slide_15.jpg",
      id: 29,
      keywords: ["js", "javascript"],
    },
    {
      link: "https://mypresentation.ru/documents_6/d9b561c144145b23946a46d2e0707068/img44.jpg",
      id: 30,
      keywords: ["js", "javascript", "for"],
    },
    {
      link: "https://www.programmingfunda.com/wp-content/uploads/2021/05/javascript-if-else-if-statement-flowchart.png",
      id: 31,
      keywords: ["js", "javascript", "if", "else", "if else", "else if"],
    },
    {
      link: "https://1.bp.blogspot.com/-O2QPHLrpkG0/XvJbZ0J3U9I/AAAAAAAAJjI/bY_w6AzdIqo1VyITcFNml_9V4VI6N-hbwCK4BGAsYHg/s1471/Blue%2BTeaching%2BMath%2BEducation%2BPresentation%2B%25284%2529.png",
      id: 32,
      keywords: [
        "js",
        "javascript",
        "if",
        "else",
        "if else",
        "else if",
        "switch",
        "case",
        "switch case",
      ],
    },
    {
      link: "https://cf2.ppt-online.org/files2/slide/9/9SrEOKlVw0JopzBNa27sj3eXMvb6ALDUxkCRihT4QF/slide-4.jpg",
      id: 33,
      keywords: ["js", "javascript", "function"],
    },
    {
      link: "https://miro.medium.com/v2/resize:fit:1400/1*4gbOh7p-CnOlEr4LK_YOiQ.png",
      id: 34,
      keywords: ["js", "javascript", "set"],
    },
    {
      link: "https://jscurious.com/wp-content/uploads/2021/01/javascript_fetch_api.jpg",
      id: 35,
      keywords: ["js", "javascript", "fetch", "api"],
    },
    {
      link: "https://i.pinimg.com/originals/7f/93/d4/7f93d488920339232e1381dce03717b4.jpg",
      id: 36,
      keywords: ["js", "javascript", "fetch", "api", "XmpHttpRequest"],
    },
    {
      link: "https://www.evkova.org/evkovaupload/job/170555/11.png",
      id: 37,
      keywords: ["js", "javascript", "server", "Ajax"],
    },
    {
      link: "https://2.bp.blogspot.com/-LfUKShLoQek/XqVp3Ln6jqI/AAAAAAAAGLs/arwgQWWuHvA0w52gBet5VEZmrwGcg_DIACLcBGAsYHQ/s1600/Callback_Logo.jpg",
      id: 38,
      keywords: ["js", "javascript", "callback"],
    },
    {
      link: "https://avatars.mds.yandex.net/i?id=ca1edcc8aaf6b7841b8040dc051b9de4-5205249-images-thumbs&n=13",
      id: 39,
      keywords: [
        "js",
        "javascript",
        "promise",
        "resolved",
        "reject",
        "pending",
        "then",
      ],
    },
    {
      link: "https://cf.ppt-online.org/files/slide/i/iMkIY5aURZjXnHmD4L9C2PTAq3cdy6QvF1uOpG/slide-34.jpg",
      id: 40,
      keywords: ["js", "javascript", "try", "catch"],
    },
    {
      link: "https://i.pinimg.com/originals/57/76/4e/57764e161e4477830b088822e859cb98.jpg",
      id: 41,
      keywords: ["react", "component"],
    },
    {
      link: "https://freetuts.net/upload/tut_post/images/2020/03/29/2343/react-js-freetuts-reactjs-la-gi-2.png",
      id: 42,
      keywords: ["react", "vitual dom", "dom", "browser dom"],
    },
    {
      link: "https://i.pinimg.com/originals/47/90/03/4790031a9fdf1b36ed9de92ee41551bd.jpg",
      id: 43,
      keywords: ["react", "props", "state"],
    },
    {
      link: "https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/c1cc056631ce4200ad2e49e78a9677f1~tplv-k3u1fbpfcp-zoom-in-crop-mark:4536:0:0:0.image",
      id: 44,
      keywords: [
        "react",
        "useState",
        "useEffect",
        "useContext",
        "useReducer",
        "useMemo",
        "useRef",
        "hook",
        "react hook",
      ],
    },
    {
      link: "https://daqxzxzy8xq3u.cloudfront.net/wp-content/uploads/2019/09/12115024/initialize-react-state-react-usestate.png",
      id: 45,
      keywords: ["react", "useState", "hook", "react hook"],
    },
    {
      link: "https://miro.medium.com/max/1400/0*hw3ulgCQYusxDJpD.png",
      id: 46,
      keywords: ["react", "useEffect", "hook", "react hook"],
    },
    {
      link: "https://webformyself.com/wp-content/uploads/2021/81/20.png",
      id: 47,
      keywords: ["react", "useContext", "hook", "react hook"],
    },
    {
      link: "https://webformyself.com/wp-content/uploads/2021/93/1.png",
      id: 48,
      keywords: ["react", "useReducer", "hook", "react hook"],
    },
    {
      link: "https://pbs.twimg.com/media/FdBw_7dXEAAS4yB.jpg:large",
      id: 49,
      keywords: ["react", "useMemo", "hook", "react hook"],
    },
    {
      link: "https://cdn.hackernoon.com/images/S0zuR5PfGFN2e1h8xuRZHD1SPBK2-7kd3h72.png",
      id: 50,
      keywords: ["react", "useRef", "hook", "react hook"],
    },
    {
      link: "https://miro.medium.com/v2/resize:fit:1400/1*Ofrw6moSMZd_xK4zc3oKNQ.png",
      id: 51,
      keywords: ["react", "jsx"],
    },
    {
      link: "https://miro.medium.com/v2/resize:fit:1400/1*dp3IYgV1eA0Etrv9I8Lm3w.png",
      id: 52,
      keywords: ["react", "react native"],
    },
    {
      link: "https://schtirlitz.ru/800/600/https/ds04.infourok.ru/uploads/ex/0879/00000878-b8f3062d/img1.jpg",
      id: 53,
      keywords: ["html", "html5"],
    },
    {
      link: "https://schtirlitz.ru/800/600/http/images.myshared.ru/6/712576/slide_5.jpg",
      id: 54,
      keywords: ["html", "html5"],
    },
    {
      link: "https://cf2.ppt-online.org/files2/slide/b/Bt5seA03TLbzcmu1DVHvqi6Z9owdn4FRgXGOPUWSY/slide-9.jpg",
      id: 55,
      keywords: ["html", "html5"],
    },
    {
      link: "http://cf.ppt-online.org/files/slide/j/jSg0U8Bwo4K697OGcfqTFidunXMPvImDRhNJl3/slide-39.jpg",
      id: 56,
      keywords: ["html", "html5", "li", "ul"],
    },
    {
      link: "http://htmlboss.ru/image/lesson10-3.jpg",
      id: 57,
      keywords: ["html", "html5", "table", "tr", "td"],
    },
    {
      link: "https://cf.ppt-online.org/files/slide/n/nJK7mce8Xy9vZCL2UF50gNuos1TdtDPrl3xBOq/slide-74.jpg",
      id: 58,
      keywords: ["html", "html5", "form"],
    },
    {
      link: "https://i.stack.imgur.com/w9ADa.jpg",
      id: 59,
      keywords: ["html", "html5", "semantic"],
    },
    {
      link: "https://blog.guvi.in/wp-content/uploads/2022/06/CSS-Box-model.png",
      id: 60,
      keywords: ["html", "html5", "box-model", "box model"],
    },
    {
      link: "https://cdn.educba.com/academy/wp-content/uploads/2019/12/CSS-Position.jpg",
      id: 61,
      keywords: [
        "html",
        "html5",
        "static",
        "relative",
        "fixed",
        "absolute",
        "z-index",
      ],
    },
    {
      link: "http://www.createafreewebsite.net/images/float-property.jpg",
      id: 62,
      keywords: ["html", "html5", "float", "rigth", "left"],
    },
    {
      link: "https://i.pinimg.com/originals/83/c7/d0/83c7d06752e6cbf1f585a4c058649742.png",
      id: 63,
      keywords: ["html", "html5", "section"],
    },
    {
      link: "https://11marketing.it/wp-content/uploads/2013/10/html5-struttura-pagina-web.jpg",
      id: 64,
      keywords: ["html", "html5", "semantic", "header", "footer", "aside"],
    },
    {
      link: "https://i2.wp.com/miro.medium.com/0*NUQsFx0WND4neCvi.png",
      id: 65,
      keywords: ["react", "layout"],
    },
  ],
};